# Generated by Django 5.0.4 on 2024-04-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('pais', models.CharField(choices=[('estados_unidos', 'Estados Unidos'), ('canada', 'Canadá'), ('reino_unido', 'Reino Unido'), ('franca', 'França'), ('alemanha', 'Alemanha'), ('japao', 'Japão'), ('china', 'China'), ('india', 'Índia'), ('australia', 'Austrália')], max_length=60)),
                ('nascimento', models.DateField()),
            ],
        ),
    ]
