# Generated by Django 5.0.4 on 2024-04-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='pais',
            field=models.CharField(choices=[('Estados Unidos', 'Estados Unidos'), ('Canadá', 'Canadá'), ('Reino Unido', 'Reino Unido'), ('França', 'França'), ('Alemanha', 'Alemanha'), ('Japão', 'Japão'), ('China', 'China'), ('Índia', 'Índia'), ('Austrália', 'Austrália')], max_length=60),
        ),
    ]
