# Generated by Django 5.0.4 on 2024-04-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0003_pessoa_criado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ['-criado']},
        ),
        migrations.AddField(
            model_name='pessoa',
            name='email',
            field=models.CharField(default='N/A', max_length=155),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=125),
        ),
    ]
